create table _USER
(
    ID BIGINT auto_increment primary key,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME  VARCHAR(255) NOT NULL,
    PASSWORD  VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    ROLE TINYINT NOT NULL,
    IS_DELETED BOOL NOT NULL
);

create table ACCOUNT
(
    ID BIGINT auto_increment primary key,
    NUMBER VARCHAR(255) NOT NULL,
    USER_ID BIGINT NOT NULL,
    IS_DELETED BOOL NOT NULL,
    constraint FK_CUSTOMER_ID foreign key (USER_ID) references _USER (ID)
);

create table CARD
(
    ID BIGINT auto_increment primary key,
    NUMBER VARCHAR(255) UNIQUE NOT NULL,
    EXPIREDATE VARCHAR(255) NOT NULL,
    CVV VARCHAR(255) NOT NULL,
    BALANCE DECIMAL(10, 2) NOT NULL,
    ACCOUNT_ID BIGINT NOT NULL,
    IS_DELETED BOOL NOT NULL,
    IS_ISSUED BOOL NOT NULL,
    constraint FK_ACCOUNT_ID foreign key (ACCOUNT_ID) references ACCOUNT (ID)
);

create table BANK_TRANSACTION
(
    ID BIGINT auto_increment primary key,
    AMOUNT DECIMAL(10, 2) NOT NULL,
    SENDER_CARD_NUMBER VARCHAR(255) NOT NULL,
    RECEIVER_CARD_NUMBER VARCHAR(255) NOT NULL,
    CREATED_AT DATE NOT NULL,
    IS_DELETED BOOL NOT NULL,
    IS_COMPLETED BOOL NOT NULL,
    constraint FK_SENDER_CARD_NUMBER foreign key (SENDER_CARD_NUMBER) references CARD (NUMBER),
    constraint FK_RECEIVER_CARD_NUMBER foreign key (RECEIVER_CARD_NUMBER) references CARD (NUMBER)
);